version: '3'
services:
  containerssh:
      build: .
      ports:
      - 127.0.0.1:2222:2222
      volumes:
      - ./containerssh.yaml:/etc/containerssh/config.yaml
      - ./host.key:/var/run/secrets/host.key
      - /var/run/docker.sock:/var/run/docker.sock
  authserver:
    build: containerssh-ldap
    volumes:
      - ./containerssh-ldap/app/main.py:/app/main.py
